### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by Amaar-V** [mlin1026/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [ ] All screenshots correspond to the described steps
  - The last screenshot for the **optimize remote running** section does not display remote running (maybe include a picture of executing WhereAmI.java from your local machine)
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Does not count keystrokes (see lab 1 part 7)
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
**Well Done!**
*Please comment on this issue if you have any questions or need clarification, thanks!*

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by mlin1026** [comment]
Hello, thanks for all the feedback. I just wanna make sure of some things before I start working.
1. Where should I include the number of keystrokes in my lab? Should I also be putting it at the optimized remote running part?
2. I suppose if I show that I put a screenshot of me running my WhereAmI.java from my local should be enough for the to fix that?
Thanks!

**Comment by mlin1026** [comment]
Hello, thanks for all the feedback. I just wanna make sure of some things before I start working.

Where should I include the number of keystrokes in my lab? Should I also be putting it at the optimized remote running part?
I suppose if I show that I put a screenshot of me running my WhereAmI.java from my local should be enough for them to fix that?
Thanks

Such as something like this? (This is all on optimizing part of the lab)
![Github reply](https://user-images.githubusercontent.com/97493164/150908152-f10a92a7-e93b-4eef-be7e-e8ef73a5926e.jpg)
!

**Comment by Amaar-V** [comment]
Hi, this screenshot is good. That and the keystroke count should go into the last step (optimizing remote learning)

**Comment by mlin1026** [comment]
Thank! From that screenshot I sent, I included 22 keystrokes to run the program twice, which is kinda over the under 10 keystroke rule in the lab, will it still work?

**Comment by Amaar-V** [comment]
Yes, that is fine! 10 was just a target to make you think but it is not required.

**Comment by mlin1026** [comment]
Hey, I'm sorry to bother, is it possible for you to quickly scan my last optimizing part to make sure that the changes I made are good? I heard there is only one chance of regrading.

**Comment by Amaar-V** [comment]
Hi, the changes you have made are good!

**Comment by Amaar-V** [comment]
Well Done!
